pipeline {
    agent any

    tools {
        python 'Python 3'  
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/Tonnyderrick/alx-backend-python.git', branch: 'main'
                sh 'git branch'  
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh '. venv/bin/activate && pytest messaging_app/tests/ --junitxml=report.xml'
            }
        }

        stage('Publish test report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
