pipeline {
    agent any

    tools {
        python 'Python 3'  // Only if using ShiningPanda and Python tool
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'admin', url: 'https://github.com/Tonnyderrick/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install --upgrade pip'
                sh '. venv/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh '. venv/bin/activate && pytest messaging_app/tests/ --junitxml=report.xml'
            }
        }

        stage('Archive report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
