#!/bin/bash

echo "🚀 Deploying Blue and Green versions..."
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml

echo "🔄 Applying Service Configuration..."
kubectl apply -f kubeservice.yaml

echo "📋 Getting Pods..."
kubectl get pods -l app=messaging-app

echo "📜 Checking logs for green deployment..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
